export const QUESTIONS = [
  "Das mache ich nach dem Aufstehen als erstes",
  "Ein Getränk",
  "Ein Fußballverein",
  "Zigaretten- und Tabakmarken",
  "Zeichentrickcharaktere",
  "Scheidungsgründe",
  "Elemente des Periodensystems",
  "Ein Gebrauchsgegenstand",
  "Flüssigkeiten",
  "Ein Fluss oder See",
  "Etwas zum Lesen",
  "Ein Wassertier",
  "Pizza- und Nudelgerichte",
  "Eine Frucht",
  "Eine bekannte Persönlichkeit",
  "Eistruhe",
  "Krankheiten",
  "Käsetheke",
  "Städte in NRW",
  "TV- und Radiosender",
  "Beleidigungen",
  "Ein Landtier",
  "Materialien",
  "Kosenamen",
  "Gründe Friedrich Merz zu hassen",
  "Ein Werkzeug",
  "Wörter für Genitalien",
  "Eine Stadt in Deutschland",
  "Ein Säugetier",
  "Verwandte",
  "Gründe, eine Verabredung abzusagen",
  "Süßigkeiten",
  "Ein Wort mit der Endung „-ung“",
  "Tatwaffen",
  "Obst und Gemüse",
  "Brötchentheke",
  "Kündigungsgründe",
  "Teil eines Kraftfahrzeugs",
  "Spiele",
  "Fortbewegungsmittel",
  "Serien",
  "Etwas aus diesem Raum",
  "Ein Wort mit der Endung „-los“",
  "Technologieunternehmen",
  "Etwas aus Holz",
  "Ein Wohnungsgegenstand",
  "Ein Wort mit der Endung „-heit“",
  "Eine Stadt im Ausland",
  "Ein Vorname",
  "Ein Land",
  "Eine Tätigkeit",
  "Ein Getränk",
  "Berg oder Gebirge",
  "Kosmetik",
  "Ein Wort mit ck",
  "Ein Wort, das mit z endet",
  "Auto- und Motorradmarken",
  "Teil des menschlichen Körpers",
  "Eine Sportart",
  "Ein Opfer",
  "Gewürze",
  "Eine Blume",
  "Teil eines Gebäudes",
  "Ein Musikinstrument",
  "Wursttheke",
  "Etwas aus Glas",
  "Interpret*innen",
  "Märchencharaktere",
  "Sehenswürdigkeiten",
  "Autokennzeichen",
  "Teil des Fahrrads",
  "Eine Pflanze",
  "Etwas aus dem Garten",
  "Synonyme für Kacke",
  "Eine Farbe",
  "Speise oder Nahrungsmittel",
  "Ein Kleidungsstück",
  "Ein Beruf",
  "Filme",
  "Wörter mit gleichen Anfangs- und Endbuchstaben",
  "Ein Tier, das fliegen kann",
  "Habe ich heute schon angefasst",
  "Fahrradmarken",
  "Schlickereien",
  "Sommeraktivität",
  "Sprache",
  "Urlaubsland",
  "Haustier",
  "Schriftsteller*in",
  "Held",
  "Geschäft",
  "Schauspieler*in",
  "Wetter",
  "Feiertag",
  "Leckerbissen",
  "Charakterzug",
  "Ein Frühstück",
"Ein Dessert",
"Eine Eissorte",
"Ein Brotbelag",
"Ein Restaurant",
"Ein Küchengerät",
"Etwas im Kühlschrank",
"Etwas im Badezimmer",
"Etwas im Schlafzimmer",
"Etwas in der Küche",
"Etwas im Büro",
"Etwas in einer Schule",
"Etwas im Supermarkt",
"Etwas auf einer Baustelle",
"Etwas auf einem Bahnhof",
"Etwas am Strand",
"Etwas im Urlaub",
"Etwas im Koffer",
"Etwas auf einer Party",
"Etwas im Auto",
"Etwas im Geldbeutel",
"Etwas an einem Schreibtisch",
"Etwas auf dem Dachboden",
"Etwas im Keller",
"Etwas, das man werfen kann",
"Etwas, das man aufblasen kann",
"Etwas, das stinkt",
"Etwas, das klebt",
"Etwas, das laut ist",
"Etwas, das leuchtet",
"Etwas, das kalt ist",
"Etwas, das heiß ist",
"Etwas, das rund ist",
"Etwas, das weich ist",
"Etwas, das zerbrechen kann",
"Etwas, das man sammelt",
"Etwas, das man verliert",
"Etwas, das man verleihen kann",
"Etwas, das man nicht teilen möchte",
"Etwas, das man heimlich macht",
"Etwas, das nervt",
"Etwas Peinliches",
"Etwas Gefährliches",
"Etwas Wertvolles",
"Etwas Ekliges",
"Etwas Süßes",
"Etwas Salziges",
"Etwas Scharfes",
"Etwas Gesundes",
"Etwas Ungesundes",
"Ein Haushaltsgerät",
"Ein Möbelstück",
"Ein Elektrogerät",
"Ein Spielzeug",
"Ein Büroartikel",
"Ein Schulfach",
"Ein Studienfach",
"Ein Verein",
"Eine Automarke",
"Eine App",
"Eine Website",
"Eine Software",
"Eine Hunderasse",
"Eine Katzenrasse",
"Ein Insekt",
"Ein Reptil",
"Ein Meerestier",
"Ein Bauernhoftier",
"Ein Zootier",
"Ein Raubtier",
"Ein Fantasiewesen",
"Ein Superheld",
"Ein Bösewicht",
"Ein Kinderbuch",
"Ein Buchtitel",
"Ein Songtitel",
"Ein Podcast",
"Ein Brettspiel",
"Ein Videospiel",
"Ein Kartenspiel",
"Ein Hobby",
"Ein Reiseziel",
"Eine Hauptstadt",
"Eine Insel",
"Ein Fluss in Deutschland",
"Eine Sprache Europas",
"Ein Getränk mit Alkohol",
"Ein Cocktail",
"Ein Snack",
"Ein Fast-Food-Gericht",
"Eine Pizzabelag",
"Ein Nudelgericht",
"Ein Gewässer",
"Ein Kleidungsaccessoire",
"Ein Schmuckstück",
"Ein Körperpflegeprodukt",
"Ein Beruf mit Uniform",
"Ein Handwerksberuf",
];
