export const QUESTIONS = [
  "Das mache ich nach dem Aufstehen am liebsten",
  "Ein Getränk",
  "Ein Fußballverein",
  "Zigaretten- und Tabakmarken",
  "Zeichentrickcharaktere",
  "Scheidungsgründe",
  "Elemente des Periodensystems",
  "Ein Gebrauchsgegenstand",
  "Flüssigkeiten",
  "Ein Fluss oder See",
  "Etwas zum Lesen",
  "Ein Wassertier",
  "Pizza- und Nudelgerichte",
  "Eine Frucht",
  "Eine bekannte Persönlichkeit",
  "Eistruhe",
  "Krankheiten",
  "Käsetheke",
  "Städte in NRW",
  "TV- und Radiosender",
  "Beleidigungen",
  "Ein Landtier",
  "Materialien",
  "Kosenamen",
  "Gründe Friedrich Merz zu hassen",
  "Ein Werkzeug",
  "Wörter für Genitalien",
  "Eine Stadt in Deutschland",
  "Ein Säugetier",
  "Verwandte",
  "Gründe, eine Verabredung abzusagen",
  "Süßigkeiten",
  "Ein Wort mit der Endung „-ung“",
  "Tatwaffen",
  "Obst und Gemüse",
  "Brötchentheke",
  "Kündigungsgründe",
  "Teil eines Kraftfahrzeugs",
  "Spiele",
  "Fortbewegungsmittel",
  "Serien",
  "Etwas aus diesem Raum",
  "Ein Wort mit der Endung „-los“",
  "Technologieunternehmen",
  "Etwas aus Holz",
  "Ein Wohnungsgegenstand",
  "Ein Wort mit der Endung „-heit“",
  "Eine Stadt im Ausland",
  "Ein Vorname",
  "Ein Land",
  "Eine Tätigkeit",
  "Ein Getränk",
  "Berg oder Gebirge",
  "Kosmetik",
  "Ein Wort mit ck",
  "Ein Wort, das mit z endet",
  "Auto- und Motorradmarken",
  "Teil des menschlichen Körpers",
  "Eine Sportart",
  "Ein Opfer",
  "Gewürze",
  "Eine Blume",
  "Teil eines Gebäudes",
  "Ein Musikinstrument",
  "Wursttheke",
  "Etwas aus Glas",
  "Interpret*innen",
  "Märchencharaktere",
  "Sehenswürdigkeiten",
  "Autokennzeichen",
  "Teil des Fahrrads",
  "Eine Pflanze",
  "Etwas aus dem Garten",
  "Synonyme für Kacke",
  "Eine Farbe",
  "Speise oder Nahrungsmittel",
  "Ein Kleidungsstück",
  "Ein Beruf",
  "Filme",
  "Wörter mit gleichen Anfangs- und Endbuchstaben",
  "Ein Tier, das fliegen kann"
];
